### PR TITLE
Fix 'Registy' typo.

### PR DESCRIPTION
**Pull request by tomcur**
Fixes a typo in the code (and its reference in the README): 'Registy' should be 'Registry'.

### CODE REVIEW

**Comment by tomcur** [comment]
Oops -- PR was created from the wrong source branch. I'll open a new PR tomorrow.

**Comment by wranders** [comment]
Actually, I just noticed that `master` is the most current. Guess I forgot to switch branches with the last update.

I've been out of Eve for a little while due to RL, but since there's still interest in this project, I'll reopen this PR (since it was technically using the correct branch) and give everything a look-over, including CCP's docs.

Thanks for contributing!

**Comment by tomcur** [comment]
I was planning to make individual pull requests for each change; I have branches set up with commits from each individual change applied. So if desired I can still make a pull request to your master (or development) branch for each individual change.

**Comment by wranders** [comment]
Separate PRs are fair.

At this point, if the commits aren't changing market orders or industry blueprints and jobs, use whichever you like. If the commits are, please use `dev`.

I'll be merging everything after all this to fix my mistake.

**Pull request closed without merging**
